repository: ELEC3542/elec3542.github.io

title: ELEC3542
description: Advanced Programming and Application Development

defaults:
  - scope:
      path: ""
    values:
      image: /images/logo.png

google_analytics: UA-90045125-1

theme: jekyll-theme-cayman

timezone: Asia/Hong_Kong

gems:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
